course_name = "电路与电子学I"
course_code = "EE1018"

notices = """
注意，电路与电子技术实验I[EE1021](https://hoa.moe/docs/fresh-spring/ee1021/)独立设课。

22 级及以前，计科专业开设电工与电子技术[EE1005](https://github.com/WDGaster703/HITSZ-OpenCS/tree/main/大一下/电工与电子技术)。23 级计算机与电子通信集群和其他电类专业一起开设电路与电子学[EE1013](https://hoa.moe/docs/fresh-spring/ee1013/)，24级起计算机与电子通信集群开设电路与电子学I。

本门课为电路和模电部分，关于这两部分更详细的资料可以参考：
[电路IA](https://hoa.moe/docs/fresh-spring/ee1011a/)
[模拟电子技术基础](https://hoa.moe/docs/sophomore-spring/ee1007/)
"""

[[lecturers]]
name = "曹玲玲"
  [[lecturers.reviews]]
  content = """
负责电路部分
老师声音好听，十分温柔，授课讲解思路清晰。
课堂 PPT 知识点总结十分到位，例题大多为教材例题。PPT 老师会在课前下发供同学们预习。
同学们的疑问老师都会在 QQ群 耐心解答，批改完作业后老师还会挑出部分作业题进行讲解。
"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "张瑞宏"
  [[lecturers.reviews]]
  content = """
负责模电部分
老师教学经验丰富，课讲得非常好，平易近人（本科计算机的，硕士转电气，对计算机学生有同感）但美中不足的是老师有一点口音（比如字母I的发音，老师念着有点像字母A），同学们可能需要一段时间适应。
PPT 内容非常全面，知识点总结很到位，还有部分内容是教材上没有的，而且教材上有些许错误。PPT 会在课程开始时下发至 QQ群，课后可能会对 PPT 进行修改然后下发最新版本。
老师很乐意解答同学们的疑惑，课堂中会问大家是否有不理解的地方，课程结束后每一章的作业老师都会专门抽空进行讲解。
"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "梁仲明"
  [[lecturers.reviews]]
  content = """
老师不太会普通话，香港人、广谱+粤语，可能一些同学听起来会比较有障碍。
上课以PPT为主，由于语言的关系，建议大家客气那好好预习一下。
如果做好了预习、自学工作，可以考虑在课堂上做题/查漏补缺。
答疑直接问老师，老师一般会用英文回答。
"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "孙丽"
  [[lecturers.reviews]]
  content = "2025春，负责计算机与电子通信1-8班的电路部分。"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "吴婷"
  [[lecturers.reviews]]
  content = "2025春，负责计算机与电子通信1-8班的模电部分。"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "詹瀚林"
  [[lecturers.reviews]]
  content = "2025春，负责计算机与电子通信9-16班的电路部分。"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "谷雨"
  [[lecturers.reviews]]
  content = "2025春，负责计算机与电子通信9-16班的模电部分。"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "和军平"
  [[lecturers.reviews]]
  content = "2025春，负责计算机与电子通信17-20班的电路部分。"
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "梁高琪"
  [[lecturers.reviews]]
  content = "2025春，负责计算机与电子通信17-20班的模电部分。"
  author = { name = "", link = "", date = "" }

textbooks = []

[[online_resources]]
title = "中国大学MOOC 《电工学》 哈尔滨工业大学 张继红"
url = "http://163.lu/JcZBg3"
description = ""
author = { name = "", link = "", date = "" }

[[online_resources]]
title = "中国大学MOOC 《模拟电子技术基础》 哈尔滨工业大学 王淑娟"
url = "http://163.lu/sLnVv4"
description = ""
author = { name = "", link = "", date = "" }

course = []

[[exam]]
content = """
# 原电工与电子技术部分
课程结束后老师会发知识点复习总结，模电的复习总结很精炼，对各种放大电路的计算进行了整理，考试前老师会出一套模拟试卷给大家自测查漏补缺并进行详细讲解。
考试难度不大，大题几乎全部是作业题，即教材的课后习题。但选择题和填空题会有比较多的坑，一不留神就会犯错的那种，需要格外小心。大题题型作业全覆盖。
然而，根据大家的反馈，打分相当不友好，可能有来路不明的扣分。每年考试完都有大量的同学去复核分数，但是大多无功而返。
最高分应该是有满分大佬的，平均分不太清楚，个人觉得相较于其他考试课，这门课程平均分应该算是比较高的了。
老师应该是会尽量捞人的，挂科人数不太清楚，但由于上网课部分同学有点松懈，应该还是有一定的同学不留神挂科了的。
"""
author = { name = "", link = "", date = "" }

[[exam]]
content = """
# 电路与电子学I部分
24 级难度超级大，挂科率高于20%，大部分人无法完成卷子。
"""
author = { name = "", link = "", date = "" }

lab = []

advice = []

[[schedule]]
content = """
2025 春电路与电子学I授课内容摘要：
电路部分（共32学时）：
第一章：电路元件和电路定律（5学时）
第二章：线性电路的稳态分析（10学时）
第三章：正弦电流电路的稳态分析（12学时）
第四章：非正弦周期电路的分析与应用（5学时）

模电部分（共32学时）：
第五章：常用半导体器件（5学时）
第六章：基本放大电路（6学时）
第七章：集成运算放大电路（6学时）
第八章：放大电路中的反馈（5学时）
第九章：信号的运算和处理（4学时）
第十章：信号的发生和信号的转换（6学时）
"""
author = { name = "", link = "", date = "" }

related_links = []

misc = []